# Use the dark Cayman theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Swaminathan Sundar"
description: "Operations Research, Machine Learning, Quantitative Research"

# Enable custom CSS
sass:
  sass_dir: assets/css
