# _config.yml
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Swaminathan Sundar"
description: "Operations Research, Machine Learning, Quantitative Research"
logo: "https://github.com/swaminathan1296.png"